seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#62594F'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#AD9274'
  medium_color: '#ede8e4'
  light_color: '#E0CCB5'
  v-light_color: '#FAF6F0'
  featured_color: '#E4EAF2'
  accent_color: '#E6E4F2'
